java2nb:
  uploadPath: /var/pic/
  username: admin
  password: 111111
logging:
  level:
    root: info
    com.java2nb: debug
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: test123456
    # 连接超时时间（毫秒）
    timeout: 10000


