java2nb:
  uploadPath: /var/pic/
  username: admin
  password: 111111
logging:
  level:
    root: info
    com.java2nb: debug
spring:
  datasource:
    driverClassName: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:absolutepath:${user.dir}/config/shardingsphere-jdbc.yml
  redis:
    host: 127.0.0.1
    port: 6379
    password: test123456
    # 连接超时时间（毫秒）
    timeout: 10000


